web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/var/docker/gitlab/config:/etc/gitlab'
    - '/var/docker/gitlab/logs:/var/log/gitlab'
    - '/var/docker/data:/var/opt/gitlab'
